"""add_kra_items_table

Revision ID: 18ea14265cbb
Revises: d60c1b165314
Create Date: 2026-07-10 02:56:24.488460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ea14265cbb'
down_revision: Union[str, None] = 'd60c1b165314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kra_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('weightage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_metric', sa.String(length=255), nullable=True),
    sa.Column('cycle', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'in_progress', 'review_submitted', 'completed', 'rejected', name='kra_status'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('employee_self_rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('employee_comment', sa.Text(), nullable=True),
    sa.Column('manager_rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['company_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['company_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kra_items_company_id'), 'kra_items', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kra_items_company_id'), table_name='kra_items')
    op.drop_table('kra_items')
    # ### end Alembic commands ###
