"""Add approved_by to Document

Revision ID: 23625093f55a
Revises: ddf024af58cd
Create Date: 2026-09-02 18:32:32.389175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23625093f55a'
down_revision: Union[str, None] = 'ddf024af58cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'company_users', ['approved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Backfill logic
    from sqlalchemy import text
    import json
    conn = op.get_bind()
    conn.execute(text("""
        UPDATE documents d
        SET approved_by = sub.actor_id
        FROM (
            SELECT entity_id, actor_id,
                   ROW_NUMBER() OVER(PARTITION BY entity_id ORDER BY created_at DESC) as rn
            FROM activity_logs
            WHERE action = 'document.updated'
              AND metadata->'updated_fields' ? 'status'
        ) sub
        WHERE d.id = sub.entity_id
          AND d.status = 'verified'
          AND sub.rn = 1;
    """))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'approved_by')
    # ### end Alembic commands ###
