"""phase2_auditease

Revision ID: 331ba914cf74
Revises: 4709dd02ce22
Create Date: 2026-07-09 06:08:20.435608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '331ba914cf74'
down_revision: Union[str, None] = '4709dd02ce22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schema_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('has_children', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['ledger_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_groups_company_id'), 'ledger_groups', ['company_id'], unique=False)
    op.create_table('audit_engagements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_label', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('invited', 'active', 'closed', name='engagement_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['company_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_engagements_company_id'), 'audit_engagements', ['company_id'], unique=False)
    op.create_table('trial_balance_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ledger_code', sa.String(length=100), nullable=True),
    sa.Column('ledger_name', sa.String(length=255), nullable=False),
    sa.Column('mapped_group_id', sa.UUID(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['mapped_group_id'], ['ledger_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_balance_accounts_company_id'), 'trial_balance_accounts', ['company_id'], unique=False)
    op.create_table('audit_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'approved', 'rejected', name='audit_entry_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['auditors.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entries_engagement_id'), 'audit_entries', ['engagement_id'], unique=False)
    op.create_table('auditor_engagement_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auditor_id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'accepted', 'revoked', name='grant_status'), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['auditors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditor_engagement_grants_auditor_id'), 'auditor_engagement_grants', ['auditor_id'], unique=False)
    op.create_index(op.f('ix_auditor_engagement_grants_engagement_id'), 'auditor_engagement_grants', ['engagement_id'], unique=False)
    op.create_table('queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('opened_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='query_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagements.id'], ),
    sa.ForeignKeyConstraint(['opened_by'], ['auditors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_engagement_id'), 'queries', ['engagement_id'], unique=False)
    op.create_table('audit_entry_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.Enum('debit', 'credit', name='entry_line_side'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['audit_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_id'], ['trial_balance_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.Enum('company_user', 'auditor', name='sender_type'), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('attached_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attached_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('raised_by', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'fulfilled', name='request_status'), nullable=False),
    sa.Column('fulfilled_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagements.id'], ),
    sa.ForeignKeyConstraint(['fulfilled_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['auditors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_requests_engagement_id'), 'requirement_requests', ['engagement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirement_requests_engagement_id'), table_name='requirement_requests')
    op.drop_table('requirement_requests')
    op.drop_table('query_messages')
    op.drop_table('audit_entry_lines')
    op.drop_index(op.f('ix_queries_engagement_id'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_auditor_engagement_grants_engagement_id'), table_name='auditor_engagement_grants')
    op.drop_index(op.f('ix_auditor_engagement_grants_auditor_id'), table_name='auditor_engagement_grants')
    op.drop_table('auditor_engagement_grants')
    op.drop_index(op.f('ix_audit_entries_engagement_id'), table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_trial_balance_accounts_company_id'), table_name='trial_balance_accounts')
    op.drop_table('trial_balance_accounts')
    op.drop_index(op.f('ix_audit_engagements_company_id'), table_name='audit_engagements')
    op.drop_table('audit_engagements')
    op.drop_index(op.f('ix_ledger_groups_company_id'), table_name='ledger_groups')
    op.drop_table('ledger_groups')
    op.drop_table('report_templates')
    # ### end Alembic commands ###
