"""fk_name

Revision ID: 4709dd02ce22
Revises: 70e5eedbe8e8
Create Date: 2026-07-09 06:00:49.542754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4709dd02ce22'
down_revision: Union[str, None] = '70e5eedbe8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_documents_current_version_id', 'documents', 'document_versions', ['current_version_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_current_version_id', 'documents', type_='foreignkey')
    # ### end Alembic commands ###
