"""Add rejection comment to AuditEntry

Revision ID: a1a6d2477372
Revises: ff50c2eb5b28
Create Date: 2026-07-10 06:48:53.603307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a6d2477372'
down_revision: Union[str, None] = 'ff50c2eb5b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_entries', sa.Column('rejection_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_entries', 'rejection_comment')
    # ### end Alembic commands ###
