"""extend_company_user_roles_hierarchy

Revision ID: cd98ce56a9c3
Revises: e05b5c558dd5
Create Date: 2026-07-10 02:50:55.007685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd98ce56a9c3'
down_revision: Union[str, None] = 'e05b5c558dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'manager'")
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'employee'")

    op.add_column('company_users', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.add_column('company_users', sa.Column('full_name', sa.String(length=255), server_default='Unknown', nullable=False))
    op.add_column('company_users', sa.Column('designation', sa.String(length=255), nullable=True))
    op.add_column('company_users', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('company_users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_foreign_key('fk_company_users_manager_id', 'company_users', 'company_users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_company_users_manager_id', 'company_users', type_='foreignkey')
    op.drop_column('company_users', 'is_active')
    op.drop_column('company_users', 'department')
    op.drop_column('company_users', 'designation')
    op.drop_column('company_users', 'full_name')
    op.drop_column('company_users', 'manager_id')
    # ### end Alembic commands ###
