"""phase34_compliance

Revision ID: e05b5c558dd5
Revises: 331ba914cf74
Create Date: 2026-07-09 06:13:02.959011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e05b5c558dd5'
down_revision: Union[str, None] = '331ba914cf74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('domain', sa.Enum('secretarial', 'roc', name='compliance_domain'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_file_id', sa.UUID(), nullable=True),
    sa.Column('metadata_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('due_date_rule', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_file_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_types_company_id'), 'document_types', ['company_id'], unique=False)
    op.create_table('meeting_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_type_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('structured_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_records_company_id'), 'meeting_records', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_records_company_id'), table_name='meeting_records')
    op.drop_table('meeting_records')
    op.drop_index(op.f('ix_document_types_company_id'), table_name='document_types')
    op.drop_table('document_types')
    # ### end Alembic commands ###
