"""Add title to RequirementRequest

Revision ID: ff50c2eb5b28
Revises: 18ea14265cbb
Create Date: 2026-07-10 06:43:59.617355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff50c2eb5b28'
down_revision: Union[str, None] = '18ea14265cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement_requests', sa.Column('title', sa.String(length=255), server_default='Requirement', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirement_requests', 'title')
    # ### end Alembic commands ###
